version: "3.8"

services:
  medusa:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    environment:
      # Postgres Database connection details
      DATABASE_URL: postgres://postgres:Jashu@3337@db:5432/my_medusa_db
      REDIS_URL: redis://redis:6379
    depends_on:
      - db
      - redis

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: my_medusa_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Jashu@3337
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6
    ports:
      - "6379:6379"

volumes:
  postgres_data:
    driver: local